server {
    listen 80;
    listen [::]:80;
    listen 127.0.0.1:8080;
    server_name chrono-mini-portal.gaocc.cc;

    root /var/www/chrono-mini-portal;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(?:css|js|png|jpg|jpeg|gif|webp|svg|ico|woff2?)$ {
        expires 7d;
        add_header Cache-Control "public";
        try_files $uri =404;
    }
}
